services:
  db:
    image: postgres:16
    container_name: fx_db
    environment:
      POSTGRES_USER: fx
      POSTGRES_PASSWORD: fx_password_change_me
      POSTGRES_DB: fxapp
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db_data:
